on:
  workflow_call:
    inputs:
      system:
        type: string
      runs-on:
        type: string
      release:
        type: string
jobs:
  build:
    runs-on: ${{ inputs.runs-on }}
    permissions:
      contents: read
      id-token: write
      attestations: write
    outputs:
      name: ${{ steps.build.outputs.name }}
      digest: ${{ steps.upload-artifact.outputs.artifact-digest }}
    env:
      flakeref: .#hydraJobs.${{ inputs.release }}.amazonImage.${{ inputs.system }}
    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
      - uses: DeterminateSystems/nix-installer-action@7993355175c2765e5733dae74f3e0786fe0e5c4f # v12
        with:
          # HACK: lets lie that we support kvm. make-disk-image.nix is fast enough in emulation mode
          # and aarch64 has no kvm on github actions
          extra-conf: extra-system-features = kvm
      - run: |
          out=$(nix build -L "$flakeref" --print-out-paths)
          echo "out=$out" >> "$GITHUB_OUTPUT"
          echo "name=$(basename "$out")" >> "$GITHUB_OUTPUT"
        id: build
        env:
          flakeref: .#hydraJobs.${{ inputs.release }}.amazonImage.${{ inputs.system }}
      - uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # v4
        id: upload-artifact
        with:
          name: ${{ steps.build.outputs.name }}
          path: ${{ steps.build.outputs.out }}
      # TODO: use https://github.com/arianvp/nix-attest to store more provenance information
      - uses: actions/attest-build-provenance@c074443f1aee8d4aeeae555aebba3282517141b2 # v2.2.3
        if: github.ref == 'refs/heads/main'
        with:
          subject-name: ${{ steps.build.outputs.name }}
          subject-digest: sha256:${{ steps.upload-artifact.outputs.artifact-digest }}
  upload:
    runs-on: ubuntu-latest
    needs: [build]
    environment: images
    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
      - uses: actions/download-artifact@95815c38cf2ff2164869cbab79da8d1f422bc89e # v4.2.1
        id: download-artifact
        with:
          name: ${{ needs.build.outputs.name }}
          path: ./result
      - uses: DeterminateSystems/nix-installer-action@7993355175c2765e5733dae74f3e0786fe0e5c4f # v12
      - uses: aws-actions/configure-aws-credentials@ececac1a45f3b08a01d2dd070d28d111c5fe6722 # v4.1.0
        with:
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/upload-ami
          aws-region: ${{ vars.AWS_REGION }}
      - run: |
          image_ids=$(nix run .#upload-ami -- --image-info "$image_info" --prefix "smoketest/" --s3-bucket "$images_bucket")
          echo "image_ids=$image_ids" >> "$GITHUB_OUTPUT"
        id: upload-smoketest
        env:
          image_info: ./result/nix-support/image-info.json
      - uses: actions/attest@a63cfcc7d1aab266ee064c58250cfc2c7d07bc31 # v2.1.1
        with:
          subject-name: ${{ needs.build.outputs.name }}
          subject-digest: ${{ needs.build.outputs.digest }}
          predicate-type: "https://github.com/nixos/amis/predicates/upload-ami/v0"
          predicate: |
            {
              "accountId": "${{ vars.AWS_ACCOUNT_ID }}",
              "imageIds": ${{ steps.upload-smoketest.outputs.image_ids }},
              "roleArn": "arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/upload-ami"
            }
