name: Upload AMI
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  build-and-upload:
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-${{ matrix.release }}-${{ matrix.system.runs-on }}-${{ matrix.system.system }}
      cancel-in-progress: true
    permissions:
      id-token: write
      attestations: write
      contents: read
    strategy:
      fail-fast: false
      matrix:
        release:
          - nixos_2411
          # - nixos_unstable
        system:
          - runs-on: ubuntu-latest
            system: x86_64-linux
          # - runs-on: ubuntu-24.04-arm
          # system: aarch64-linux
    uses: ./.github/workflows/build-and-upload.yml
    with:
      runs-on: ${{ matrix.system.runs-on }}
      system: ${{ matrix.system.system }}
      release: ${{ matrix.release }}
  delete-deprecated-images:
    runs-on: ubuntu-latest
    needs: [upload-ami]
    environment: images
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: DeterminateSystems/nix-installer-action@7993355175c2765e5733dae74f3e0786fe0e5c4f # v12
      - uses: DeterminateSystems/magic-nix-cache-action@87b14cf437d03d37989d87f0fa5ce4f5dc1a330b # v8
      - uses: aws-actions/configure-aws-credentials@ececac1a45f3b08a01d2dd070d28d111c5fe6722 # v4.1.0
        with:
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/upload-ami
          aws-region: ${{ vars.AWS_REGION }}
      - name: Delete deprecated AMIs
        if: github.ref == 'refs/heads/main'
        run: nix run .#delete-deprecated-images
