name: Upload AMI
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  build-and-upload:
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-${{ matrix.release }}-${{ matrix.system.runs-on }}-${{ matrix.system.system }}
      cancel-in-progress: true
    permissions:
      id-token: write
      attestations: write
      contents: read
    strategy:
      fail-fast: false
      matrix:
        release:
          - nixos_2411
          # - nixos_unstable
        system:
          - runs-on: ubuntu-latest
            system: x86_64-linux
          - runs-on: ubuntu-24.04-arm
            system: aarch64-linux
    uses: ./.github/workflows/build-and-upload.yml
    with:
      runs-on: ${{ matrix.system.runs-on }}
      system: ${{ matrix.system.system }}
      release: ${{ matrix.release }}
  delete-deprecated-images:
    name: Delete deprecated images
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: build-and-upload
    environment: images
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: DeterminateSystems/nix-installer-action@e50d5f73bfe71c2dd0aa4218de8f4afa59f8f81d # v16
      - uses: aws-actions/configure-aws-credentials@ececac1a45f3b08a01d2dd070d28d111c5fe6722 # v4.1.0
        with:
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/upload-ami
          aws-region: ${{ vars.AWS_REGION }}
      - name: Delete deprecated AMIs
        if: github.ref == 'refs/heads/main'
        run: "nix run .#delete-deprecated-images"
  deploy-pages:
    name: Deploy images page
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: [build-and-upload, delete-deprecated-images]
    permissions:
      contents: read
      id-token: write
      pages: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: DeterminateSystems/nix-installer-action@e50d5f73bfe71c2dd0aa4218de8f4afa59f8f81d # v16
      - uses: aws-actions/configure-aws-credentials@ececac1a45f3b08a01d2dd070d28d111c5fe6722 # v4.1.0
        with:
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/github-pages
          aws-region: ${{ vars.AWS_REGION }}
      - name: Describe images
        run: nix run .#describe-images > ./site/images.json
      - name: Upload pages
        uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa # v3.0.1
        with:
          path: ./site
      - name: Deploy pages
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4.0.5
        id: deployment
